2019-08-12 19:18:35,033 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-12 19:18:56,262 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-12 19:18:58,306 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-12 19:23:49,015 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:10:27,200 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:12:16,495 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:12:21,777 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:44:31,436 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:45:18,199 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:45:39,423 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:46:00,433 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:46:07,606 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:56:12,375 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-13 20:56:25,568 ERROR: Exception on /user/antra [GET] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Projects\FlaskMegaTutorial\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\user.html", line 11, in block "content"
    <p>{{ user.followers.count() }} followers, {{ users.followed.count() }} following.</p>
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'users' is undefined
2019-08-13 20:56:59,951 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 07:28:14,831 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 07:39:59,626 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 07:40:59,128 ERROR: Exception on /explore [GET] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 138, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Projects\FlaskMegaTutorial\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2019-08-17 07:41:40,979 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 07:49:40,587 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 07:54:43,780 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:46]
2019-08-17 16:02:27,491 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:49:28,164 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:49:58,631 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:52:00,376 ERROR: Exception on /reset_password_request [POST] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 14, in send_password_reset_email
    token = user.get_password_reset_token()
AttributeError: 'User' object has no attribute 'get_password_reset_token'
2019-08-17 16:53:10,178 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:54:29,911 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:55:25,957 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
