2019-10-25 22:33:26,983 ERROR: Exception on /index [GET] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\Projects\FlaskMegaTutorial\app\main\routes.py", line 44, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Projects\FlaskMegaTutorial\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 26, in block "navbar"
    <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.search'. Did you mean 'main.user' instead?
2019-10-25 22:33:28,735 ERROR: Exception on /index [GET] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\Projects\FlaskMegaTutorial\app\main\routes.py", line 44, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Projects\FlaskMegaTutorial\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "G:\Projects\FlaskMegaTutorial\app\templates\base.html", line 26, in block "navbar"
    <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.search'. Did you mean 'main.user' instead?
2019-10-25 22:45:47,831 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:76]
